### PR TITLE
Main>Maintenance-page-colors-palette: Update color

### PR DESCRIPTION
**Pull request by gonzalo-plaza**

### CODE REVIEW

**Comment by gonzalo-plaza** [comment]
@PVillasana @Andresws12 This is okay to review.

**Comment by Andresws12** [comment]
@gonzalo-plaza please remember use the structure from discord or google docs, when you add a new branch feature/... add/..  if you don't know how start, you can ask me

**Comment by Andresws12** [comment]
@gonzalo-plaza Maybe you din't understand how add the first title from the commits' cause i don't know with yours commits where are you changing, for example.. maintenance-page-colors-palette: Test structure, are you changing the test structure from maintenance page? ig you are changing the structure why are you using the name from the branch and don't use Maintenance page > css: test structure ?

**Comment by Andresws12** [comment]
@gonzalo-plaza The problems fixed, but remember write your commits more descriptive and use the structure to create the branchs. Please, review all if all is working and tell me if the pull request is ready to code review

**Comment by gonzalo-plaza** [comment]
@Andresws12 The problem is that the branch name that I have used is to long, and when I write the branch name I haven´t many space to can write the description of the commit. I remember that must be Main > Maintenance-page-html-colors-palette : test structure of the document html, for example. I must resume the name of the branch the next time.

**Comment by gonzalo-plaza** [comment]
@Andresws12 I have review the code and the pull reques is ready to code review

**Pull request merged**
